### ISSUE TITLE
Autopilot buggy...

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/A320-family#5]
I'm currently in severe turbulence caused by the autopilot... lateral is fine but I'm going up and down like a racehorse trotting.

**Comment by jan-hudec** [comment]
Looks like the vertical axis might need some tuning. How are you setting up the turbulence so I can try to reproduce it?

Also, are you using A319, A320 or A321? I've tried to bring the models in sync last fall, but there may still be some differences. Or the differences that there should be may mean the tuning is good enough for one, but not the other.

**Comment by legoboyvdlp** [comment]
It's basically the autopilot causing turbulence ;) Just ALT HLD.
A320-231.

**Comment by jan-hudec** [comment]
Damn, I confused the two versions. This one would really deserve porting over the cockpit and systems of A320neo, or straight merging with it. Because the neo version simulates the flight laws and flight management computer and has working navigation panel and all and is generally in pretty good condition, except for the crappy FDM. I don't think this has any better FDM though.

Of course using different systems requires using corresponding autopilot too. And that seems to be better in the neo version too.

**Comment by FGDATA** [comment]
@jan-hudec 
I think many of the code of the neo could definitely be ported over the family as well.

The neo is a more advanced/designed/developed aircraft thanks to the MIA guys, particulaly  Narendran.

IH-COL
