### ISSUE TITLE
Fuel Consumption too high

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/A320-family#6]
I'm currently inbound Kansai with the planned amount of fuel from simbrief / fuelplanner. 
I have less than the amount of fuel to go to my alternate, never mind 'extra' or 'reserve'. I'm thinking that I'm going to have to glide for the last 20nm.

**Comment by legoboyvdlp** [comment]
Nevermind, I filled up with 6000lb, not kg... Gimli time?

**Comment by jan-hudec** [comment]
Well, the fuel consumption _is_ way off. This is general problem of JSBSim; JSBSim assumes constant thrust-specific fuel consumption, corrected for temperature, but in turbofans the TSFC actually increases with both speed and altitude and the cruise value is almost double the static one. So either the static value (which is more often quoted) is used and the consumption is too low, or the cruise value is used and the consumption is about right at FL360, but too high during taxi and take-off. I have not checked which case this model is, though.

And while YASim at least does not default to the absurd thrust table, I believe it is not any better in _this_ regard.

**Comment by JWocky** [comment]
Really funny how many JSB planes have ranges exactly in the specs then.

**Comment by jan-hudec** [comment]
It's not that hard to adjust the TSFC so that the range is about right when you fly the standard profile. The take-off is just a relatively short part of the flight and on approach the thrust is low, so the effect of the difference is small anyway. It is non-standard profiles that will give unrealistic results. E.g. if you did emergency descent and flight at 10,000 ft, you'd burn significantly more fuel than you should in reality.

**Comment by IAHM-COL** [comment]
Great Explanation Jan.
I always was confused about this, but now it makes more sense.

Would you say that adjusting the TFSC to the cruising values is what makes
more sense, since it is the longest track flown in most routes?

@IAHM-COL

**Comment by jan-hudec** [comment]
Yes, it makes most sense short of implementing better simulation.

And data for better simulation seem pretty hard to come by. I've lately thought about asking about this when somebody beat me to it: http://aviation.stackexchange.com/q/29045/524. The [linked lecture notes](http://soliton.ae.gatech.edu/people/dschrage/AE3310/3310%20Chapter%203.pdf) are a bit strange though, saying that “_c<sub>t</sub>_ is near constant with altitude” beside a graph that shows _c<sub>t</sub>_ rather significantly vary with altitude (p. 38).

Before that I also [asked about the default thrust table](http://aviation.stackexchange.com/q/19458/524), which is also totally off for a turbofan (it is a table for turbojet; turns out the behaviour is rather different). And I got an approximation (I believe YASim uses that one or very similar), but then [this comment kinda shots it down](https://aviation.stackexchange.com/questions/19458/how-does-turbofan-engine-performance-depend-on-speed-and-density-altutude/19466?noredirect=1#comment50991_19466) with real data that don't match the approximation at all. And the data can't be used as given either, because the P&W JT-15D has bypass ratio of just about 3, so I am not sure how representative it is of engines with bypass ration 5–6.
